### PR TITLE
Update to 1.20.2

### PR DESCRIPTION
**Pull request by JasonClarkAltmann**

### CODE REVIEW

**Comment by wadesherman** [comment]
thanks!

**Comment by twokilohertz** [comment]
haven't tested, but lgtm, can't imagine a minor version bump would require code changes

**Comment by JasonClarkAltmann** [comment]
If you use third party minecraft launchers such as "Prism Launcher" and have this mod installed and then check for updates, you get the following error message: 
"Mod name: Logical Zoom
Reason: No valid version found for this mod. It's probably unavailable for the current game version / mod loader."

**Comment by LogicalGeekBoy** [comment]
Thanks for the contribution and this is the correct way to support a newer version. On checking today I can see a few of the versions are now different so I've bumped up the versions here https://github.com/LogicalGeekBoy/logical_zoom/pull/51 and have released an updated version of the mod. Thanks again!

**Pull request closed without merging**
